### ISSUE TITLE
0.8.0 doesn't seem to be working

### ISSUE THREAD

**Issue by moT01** [coderoad/coderoad-cli#90]
Not sure if this is something on my end, I don't think it is - I tried to install the latest (0.8.0) with `npm install -g @coderoad/cli` - and the commands aren't working. I got this error when trying to check `coderoad --version`:
```sh
/usr/local/lib/node_modules/@coderoad/cli/bin/coderoad:1
Error: Cannot find module '../build/cli'
Require stack:
- /usr/local/lib/node_modules/@coderoad/cli/bin/coderoad
    at Object.<anonymous> (/usr/local/lib/node_modules/@coderoad/cli/bin/coderoad:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/@coderoad/cli/bin/coderoad' ]
}
```
That was on my mac, similar error when trying on Ubuntu.

I dug into the files - when looking at what got installed with 0.7.0, there's a `build` folder - it's not there in 0.8.0. So maybe just forgot to do some sort of build step before publishing @ShMcK?

Edits:
This is not ~a problem~ blocking me, I have just been using 0.7.0 for now.

More info: 
Adding the webhook info to a coderoad.yaml file won't build with 0.7.0 - I added them manually to test. Looking at the commits on here - I assume it will work if 0.8.0 was working.

**Comment by ShMcK** [comment]
Closed with release of v0.9
